# Run with `flutter gen-l10n`.
arb-dir: lib/l10n
template-arb-file: app_en.arb
untranslated-messages-file: untranslated_messages.txt
output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated