
// Objective-C API for talking to the following Go packages
//
//	server/binding/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libmtorrentserver_FRAMEWORK_H__
#define __Libmtorrentserver_FRAMEWORK_H__

#include "Libmtorrentserver.objc.h"
#include "Universe.objc.h"

#endif
