import 'package:mangayomi/models/source_model.dart';

String logoUrl =
    'https://comick.app/_next/image?url=%2Fstatic%2Ficons%2Funicorn-64.png&w=144&q=75';
String apiUrl = 'https://api.comick.fun/';
List<SourceModel> comickSourcesList = [
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'en',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'ar',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'pt',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'pt-br',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'it',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'ru',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'es',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'es-419',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'id',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'hi',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'de',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'ja',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'tr',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'pl',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'zh',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'zh-hk',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: 'Comick',
      url: apiUrl,
      lang: 'fr',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: "KomikLab",
      url: "https://komiklab.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: "AnimatedGlitchedScans",
      url: "https://anigliscans.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
];
