import 'package:mangayomi/models/source.dart';

const logoUrl =
    'https://comick.app/_next/image?url=%2Fstatic%2Ficons%2Funicorn-64.png&w=144&q=75';
const apiUrl = 'https://api.comick.fun';
const baseUrl = 'https://comick.app';

List<Source> get comickSourcesList => _comickSourcesList;
List<Source> _comickSourcesList = [
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'en',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ar',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt-br',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'it',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ru',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es-419',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'id',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'hi',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'de',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ja',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'tr',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pl',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh-hk',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
  Source(
      sourceName: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'fr',
      typeSource: TypeSource.comick,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss'Z'",
      dateFormatLocale: "en"),
];
