import 'package:mangayomi/models/source.dart';

List<Source> get madaraSourcesList => _madaraSourcesList;
List<Source> _madaraSourcesList = [
  Source(
      sourceName: "FR-Scan",
      baseUrl: "https://fr-scan.com",
      lang: "fr",
      typeSource: TypeSource.madara,
      logoUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "fr"),
  Source(
      sourceName: "AstralManga",
      baseUrl: "https://astral-manga.fr",
      lang: "fr",
      typeSource: TypeSource.madara,
      logoUrl: '',
      dateFormat: "dd/mm/yyyy",
      dateFormatLocale: "fr"),
  Source(
    sourceName: "Akuma no Tenshi",
    baseUrl: "https://akumanotenshi.com",
    lang: "tr",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd/MM/yyyy",
    dateFormatLocale: "pt-BR",
  ),
  Source(
    sourceName: "Adult Webtoon",
    baseUrl: "https://adultwebtoon.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    isNsfw: true,
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Adult Webtoon",
    baseUrl: "https://adultwebtoon.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    isNsfw: true,
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),

  Source(
    sourceName: "ArazNovel",
    baseUrl: "https://www.araznovel.com",
    lang: "tr",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "d MMMM yyyy",
    dateFormatLocale: "en",
  ),
  Source(
    sourceName: "BestManga",
    baseUrl: "https://bestmanga.club",
    lang: "ru",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd.MM.yyyy",
    dateFormatLocale: "ru",
  ),
  Source(
    sourceName: "Chibi Manga",
    baseUrl: "https://www.cmreader.info",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Clover Manga",
    baseUrl: "https://clover-manga.com",
    lang: "tr",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "tr",
  ),
  Source(
    sourceName: "Comictoon",
    baseUrl: "https://comictoonthaith-new.com",
    lang: "th",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMMM dd, yyyy",
    dateFormatLocale: "th",
  ),
  Source(
    sourceName: "CookieToon",
    baseUrl: "https://cookietoon.online",
    lang: "pt-BR",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd/MM/yyyy",
    dateFormatLocale: "pt-BR",
  ),
  Source(
    sourceName: "Drope Scan",
    baseUrl: "https://dropescan.com",
    lang: "pt-BR",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd/MM/yyyy",
    dateFormatLocale: "pt-BR",
  ),
  Source(
    sourceName: "EvaScans",
    baseUrl: "https://evascans.com",
    lang: "tr",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMM d, yyy",
    dateFormatLocale: "tr",
  ),
  Source(
    sourceName: "Final Scans",
    baseUrl: "https://finalscans.com",
    lang: "pt-BR",
    typeSource: TypeSource.madara,
    logoUrl: '',
    isNsfw: true,
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "pt-BR",
  ),
  Source(
    sourceName: "Glory Manga",
    baseUrl: "https://glorymanga.com",
    lang: "tr",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd/MM/yyy",
    dateFormatLocale: "tr",
  ),
  Source(
    sourceName: "Hentai Manga",
    baseUrl: "https://hentaimanga.me",
    isNsfw: true,
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "HentaiWebtoon",
    baseUrl: "https://hentaiwebtoon.com",
    isNsfw: true,
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Ikifeng",
    baseUrl: "https://ikifeng.com",
    lang: "es",
    typeSource: TypeSource.madara,
    logoUrl: '',
    isNsfw: true,
    dateFormat: "dd/MM/yyyy",
    dateFormatLocale: "es",
  ),
  Source(
    sourceName: "Inmortal Scan",
    baseUrl: "https://manga.mundodrama.site",
    lang: "es",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "es",
  ),
  Source(
    sourceName: "Its Your Right Manhua",
    baseUrl: "https://itsyourightmanhua.com/",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Kami Sama Explorer",
    baseUrl: "https://leitor.kamisama.com.br",
    lang: "pt-BR",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd 'de' MMMM 'de' yyyy",
    dateFormatLocale: "pt-BR",
  ),
  Source(
    sourceName: "KlikManga",
    baseUrl: "https://klikmanga.id",
    lang: "id",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "id",
  ),
  Source(
    sourceName: "KSGroupScans",
    baseUrl: "https://ksgroupscans.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "LHTranslation",
    baseUrl: "https://lhtranslation.net",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Lolicon",
    baseUrl: "https://lolicon.mobi",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Lord Manga",
    baseUrl: "https://lordmanga.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "MangaVisa",
    baseUrl: "https://mangavisa.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "MangaClash",
    baseUrl: "https://mangaclash.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MM/dd/yy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manga District",
    baseUrl: "https://mangadistrict.com",
    lang: "tr",
    typeSource: TypeSource.madara,
    logoUrl: '',
    isNsfw: true,
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manga-fast.com",
    baseUrl: "https://manga-fast.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "d MMMM'،' yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manga Fenix",
    baseUrl: "https://manga-fenix.com",
    lang: "es",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "es",
  ),
  Source(
    sourceName: "MangaFreak.online",
    baseUrl: "https://mangafreak.online",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "d MMMM، yyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "MangaGreat",
    baseUrl: "https://mangagreat.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manga Hentai",
    baseUrl: "https://mangahentai.me",
    lang: "en",
    isNsfw: true,
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),

  Source(
    sourceName: "MangaMe",
    baseUrl: "https://mangame.org",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd.MM.yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manga One Love",
    baseUrl: "https://mangaonelove.site",
    lang: "ru",
    typeSource: TypeSource.madara,
    logoUrl: '',
    isNsfw: true,
    dateFormat: "dd.MM.yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manga Read",
    baseUrl: "https://mangaread.co",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "yyyy-MM-dd",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "MangaRolls",
    baseUrl: "https://mangarolls.com",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manga Şehri",
    baseUrl: "https://mangasehri.com",
    lang: "tr",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "dd/MM/yyy",
    dateFormatLocale: "tr",
  ),
  Source(
    sourceName: "Mangasushi",
    baseUrl: "https://mangasushi.org",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    dateFormat: "MMMM dd, yyyy",
    dateFormatLocale: "en_US",
  ),
  Source(
    sourceName: "Manhwa18.org",
    baseUrl: "https://manhwa18.org",
    lang: "en",
    typeSource: TypeSource.madara,
    logoUrl: '',
    isNsfw: true,
    dateFormat: "MMMM d, yyyy",
    dateFormatLocale: "en_US",
  ),
];
