import 'package:mangayomi/models/source.dart';

const logoUrl = '';
const apiUrl = 'https://api.mangadex.org';
const baseUrl = 'https://mangadex.org';
const isNsfw = true;
List<Source> get mangaDexSourcesList => _mangaDexSourcesList;
List<Source> _mangaDexSourcesList = [
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'en',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ar',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt-br',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'it',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ru',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es-419',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'id',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'hi',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'de',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ja',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'tr',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pl',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh-hk',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
  Source(
      sourceName: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'fr',
      typeSource: TypeSource.mangadex,
      logoUrl: logoUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us'),
];
