// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum AidokuJsAction {
  createContext,
  evaluate,
  evaluateAsync,
  getProperty,
  destroyContext,
  webviewCreate,
  webviewSetRuleList,
  webviewLoad,
  webviewLoadHtml,
  webviewWaitForLoad,
  webviewEval,
  webviewEvalAsync,
  webviewAddUserScript,
  webviewGetCookies,
  webviewDeleteCookie,
  webviewDestroy,
}

class AidokuJsRequest {
  final int contextId;
  final AidokuJsAction action;
  final String script;
  final String? extra;

  const AidokuJsRequest({
    required this.contextId,
    required this.action,
    required this.script,
    this.extra,
  });

  @override
  int get hashCode =>
      contextId.hashCode ^ action.hashCode ^ script.hashCode ^ extra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuJsRequest &&
          runtimeType == other.runtimeType &&
          contextId == other.contextId &&
          action == other.action &&
          script == other.script &&
          extra == other.extra;
}

class AidokuJsResponse {
  final bool success;
  final String? result;
  final String? error;

  const AidokuJsResponse({required this.success, this.result, this.error});

  @override
  int get hashCode => success.hashCode ^ result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuJsResponse &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          result == other.result &&
          error == other.error;
}
