// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../aidoku_wasm/host_js.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'aidoku_wasm.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `run`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Sets a default setting value in the Aidoku engine from Dart.
Future<void> setAidokuDefaultSetting({
  required String key,
  required int valueType,
  required String value,
}) => RustLib.instance.api.crateApiAidokuWasmSetAidokuDefaultSetting(
  key: key,
  valueType: valueType,
  value: value,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AidokuSource>>
abstract class AidokuSource implements RustOpaqueInterface {
  /// Instantiates a `.wasm` module on a new dedicated thread. `request_handler`
  /// is called for every HTTP request an Aidoku source makes; wire it to
  /// `lib/services/http/m_client.dart` (or an equivalent) on the Dart side
  /// so interceptors/DoH/proxy handling keep applying. `print_handler`
  /// receives every `std.print`/`env.print` call from the WASM module.
  /// `js_handler` handles JS evaluation calls from the WASM module.
  static Future<AidokuSource> create({
    required List<int> wasmBytes,
    required String sourceKey,
    required FutureOr<AidokuNetResponse> Function(AidokuNetRequest)
    requestHandler,
    required FutureOr<void> Function(String) printHandler,
    required FutureOr<AidokuJsResponse> Function(AidokuJsRequest) jsHandler,
  }) => RustLib.instance.api.crateApiAidokuWasmAidokuSourceCreate(
    wasmBytes: wasmBytes,
    sourceKey: sourceKey,
    requestHandler: requestHandler,
    printHandler: printHandler,
    jsHandler: jsHandler,
  );

  @override
  Future<void> dispose();

  Future<AidokuSourceFeatures> features();

  Future<String?> getBaseUrl();

  Future<List<AidokuFilter>> getFilters();

  Future<AidokuImageRequest?> getImageRequest({
    required String url,
    List<(String, String)>? context,
  });

  Future<List<AidokuListing>> getListings();

  Future<AidokuMangaPage> getMangaList({
    required String listingId,
    required String listingName,
    required int page,
  });

  Future<AidokuManga> getMangaUpdate({
    required AidokuManga manga,
    required bool needsDetails,
    required bool needsChapters,
  });

  Future<List<AidokuPage>> getPageList({
    required AidokuManga manga,
    required AidokuChapter chapter,
  });

  Future<bool> handleBasicLogin({
    required String key,
    required String username,
    required String password,
  });

  Future<AidokuDeepLink?> handleDeepLink({required String url});

  Future<String> handleMigration({
    required int kind,
    required String mangaKey,
    String? chapterKey,
  });

  Future<bool> handleWebLogin({
    required String key,
    required List<(String, String)> cookies,
  });

  Future<AidokuMangaPage> searchMangaList({
    String? query,
    required int page,
    required List<AidokuFilterValue> filters,
  });
}

class AidokuChapter {
  final String key;
  final String? title;
  final double? chapterNumber;
  final double? volumeNumber;
  final PlatformInt64? dateUploaded;
  final List<String>? scanlators;
  final String? url;
  final String? language;
  final String? thumbnail;
  final bool locked;

  const AidokuChapter({
    required this.key,
    this.title,
    this.chapterNumber,
    this.volumeNumber,
    this.dateUploaded,
    this.scanlators,
    this.url,
    this.language,
    this.thumbnail,
    required this.locked,
  });

  static Future<AidokuChapter> default_() =>
      RustLib.instance.api.crateApiAidokuWasmAidokuChapterDefault();

  @override
  int get hashCode =>
      key.hashCode ^
      title.hashCode ^
      chapterNumber.hashCode ^
      volumeNumber.hashCode ^
      dateUploaded.hashCode ^
      scanlators.hashCode ^
      url.hashCode ^
      language.hashCode ^
      thumbnail.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuChapter &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          title == other.title &&
          chapterNumber == other.chapterNumber &&
          volumeNumber == other.volumeNumber &&
          dateUploaded == other.dateUploaded &&
          scanlators == other.scanlators &&
          url == other.url &&
          language == other.language &&
          thumbnail == other.thumbnail &&
          locked == other.locked;
}

class AidokuDeepLink {
  final String? mangaKey;
  final String? chapterKey;
  final AidokuListing? listing;

  const AidokuDeepLink({this.mangaKey, this.chapterKey, this.listing});

  @override
  int get hashCode =>
      mangaKey.hashCode ^ chapterKey.hashCode ^ listing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuDeepLink &&
          runtimeType == other.runtimeType &&
          mangaKey == other.mangaKey &&
          chapterKey == other.chapterKey &&
          listing == other.listing;
}

/// Simplified filter-definition payload sent to Dart (to render search UI).
/// Only the common configurations are surfaced for now (matches the ones
/// actually rendered by mangayomi's `FilterList` UI model).
class AidokuFilter {
  final String id;
  final String? title;
  final String kind;
  final List<String> options;
  final String? defaultValue;

  const AidokuFilter({
    required this.id,
    this.title,
    required this.kind,
    required this.options,
    this.defaultValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      kind.hashCode ^
      options.hashCode ^
      defaultValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuFilter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          kind == other.kind &&
          options == other.options &&
          defaultValue == other.defaultValue;
}

@freezed
sealed class AidokuFilterValue with _$AidokuFilterValue {
  const AidokuFilterValue._();

  const factory AidokuFilterValue.text({
    required String id,
    required String value,
  }) = AidokuFilterValue_Text;
  const factory AidokuFilterValue.sort({
    required String id,
    required int index,
    required bool ascending,
  }) = AidokuFilterValue_Sort;
  const factory AidokuFilterValue.check({
    required String id,
    required PlatformInt64 value,
  }) = AidokuFilterValue_Check;
  const factory AidokuFilterValue.select({
    required String id,
    required String value,
  }) = AidokuFilterValue_Select;
  const factory AidokuFilterValue.multiSelect({
    required String id,
    required List<String> included,
    required List<String> excluded,
  }) = AidokuFilterValue_MultiSelect;
  const factory AidokuFilterValue.range({
    required String id,
    double? from,
    double? to,
  }) = AidokuFilterValue_Range;
}

class AidokuImageRequest {
  final String url;
  final List<(String, String)> headers;
  final Uint8List? body;

  const AidokuImageRequest({
    required this.url,
    required this.headers,
    this.body,
  });

  @override
  int get hashCode => url.hashCode ^ headers.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuImageRequest &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          headers == other.headers &&
          body == other.body;
}

class AidokuListing {
  final String id;
  final String name;
  final bool isList;

  const AidokuListing({
    required this.id,
    required this.name,
    required this.isList,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isList.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuListing &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isList == other.isList;
}

class AidokuManga {
  final String sourceKey;
  final String key;
  final String title;
  final String? cover;
  final List<String>? artists;
  final List<String>? authors;
  final String? description;
  final String? url;
  final List<String>? tags;
  final int status;
  final int contentRating;
  final int viewer;
  final int updateStrategy;
  final PlatformInt64? nextUpdateTime;
  final List<AidokuChapter>? chapters;

  const AidokuManga({
    required this.sourceKey,
    required this.key,
    required this.title,
    this.cover,
    this.artists,
    this.authors,
    this.description,
    this.url,
    this.tags,
    required this.status,
    required this.contentRating,
    required this.viewer,
    required this.updateStrategy,
    this.nextUpdateTime,
    this.chapters,
  });

  static Future<AidokuManga> default_() =>
      RustLib.instance.api.crateApiAidokuWasmAidokuMangaDefault();

  @override
  int get hashCode =>
      sourceKey.hashCode ^
      key.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      artists.hashCode ^
      authors.hashCode ^
      description.hashCode ^
      url.hashCode ^
      tags.hashCode ^
      status.hashCode ^
      contentRating.hashCode ^
      viewer.hashCode ^
      updateStrategy.hashCode ^
      nextUpdateTime.hashCode ^
      chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuManga &&
          runtimeType == other.runtimeType &&
          sourceKey == other.sourceKey &&
          key == other.key &&
          title == other.title &&
          cover == other.cover &&
          artists == other.artists &&
          authors == other.authors &&
          description == other.description &&
          url == other.url &&
          tags == other.tags &&
          status == other.status &&
          contentRating == other.contentRating &&
          viewer == other.viewer &&
          updateStrategy == other.updateStrategy &&
          nextUpdateTime == other.nextUpdateTime &&
          chapters == other.chapters;
}

class AidokuMangaPage {
  final List<AidokuManga> entries;
  final bool hasNextPage;

  const AidokuMangaPage({required this.entries, required this.hasNextPage});

  static Future<AidokuMangaPage> default_() =>
      RustLib.instance.api.crateApiAidokuWasmAidokuMangaPageDefault();

  @override
  int get hashCode => entries.hashCode ^ hasNextPage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuMangaPage &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          hasNextPage == other.hasNextPage;
}

class AidokuNetRequest {
  final String method;
  final String url;
  final List<(String, String)> headers;
  final Uint8List? body;
  final BigInt timeoutMs;

  const AidokuNetRequest({
    required this.method,
    required this.url,
    required this.headers,
    this.body,
    required this.timeoutMs,
  });

  @override
  int get hashCode =>
      method.hashCode ^
      url.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      timeoutMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuNetRequest &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          url == other.url &&
          headers == other.headers &&
          body == other.body &&
          timeoutMs == other.timeoutMs;
}

class AidokuNetResponse {
  final int statusCode;
  final List<(String, String)> headers;
  final Uint8List body;
  final String? error;

  const AidokuNetResponse({
    required this.statusCode,
    required this.headers,
    required this.body,
    this.error,
  });

  static Future<AidokuNetResponse> default_() =>
      RustLib.instance.api.crateApiAidokuWasmAidokuNetResponseDefault();

  @override
  int get hashCode =>
      statusCode.hashCode ^ headers.hashCode ^ body.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuNetResponse &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          headers == other.headers &&
          body == other.body &&
          error == other.error;
}

@freezed
sealed class AidokuPage with _$AidokuPage {
  const AidokuPage._();

  const factory AidokuPage.url({
    required String url,
    required List<(String, String)> context,
  }) = AidokuPage_Url;
  const factory AidokuPage.text(String field0) = AidokuPage_Text;
  const factory AidokuPage.image({Uint8List? data}) = AidokuPage_Image;
  const factory AidokuPage.zipFile({
    required String url,
    required String filePath,
  }) = AidokuPage_ZipFile;
}

class AidokuSourceFeatures {
  final bool providesListings;
  final bool providesHome;
  final bool dynamicFilters;
  final bool dynamicSettings;
  final bool dynamicListings;
  final bool processesPages;
  final bool providesImageRequests;
  final bool providesBaseUrl;
  final bool handlesDeepLinks;
  final bool handlesBasicLogin;
  final bool handlesWebLogin;
  final bool handlesMigration;

  const AidokuSourceFeatures({
    required this.providesListings,
    required this.providesHome,
    required this.dynamicFilters,
    required this.dynamicSettings,
    required this.dynamicListings,
    required this.processesPages,
    required this.providesImageRequests,
    required this.providesBaseUrl,
    required this.handlesDeepLinks,
    required this.handlesBasicLogin,
    required this.handlesWebLogin,
    required this.handlesMigration,
  });

  static Future<AidokuSourceFeatures> default_() =>
      RustLib.instance.api.crateApiAidokuWasmAidokuSourceFeaturesDefault();

  @override
  int get hashCode =>
      providesListings.hashCode ^
      providesHome.hashCode ^
      dynamicFilters.hashCode ^
      dynamicSettings.hashCode ^
      dynamicListings.hashCode ^
      processesPages.hashCode ^
      providesImageRequests.hashCode ^
      providesBaseUrl.hashCode ^
      handlesDeepLinks.hashCode ^
      handlesBasicLogin.hashCode ^
      handlesWebLogin.hashCode ^
      handlesMigration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AidokuSourceFeatures &&
          runtimeType == other.runtimeType &&
          providesListings == other.providesListings &&
          providesHome == other.providesHome &&
          dynamicFilters == other.dynamicFilters &&
          dynamicSettings == other.dynamicSettings &&
          dynamicListings == other.dynamicListings &&
          processesPages == other.processesPages &&
          providesImageRequests == other.providesImageRequests &&
          providesBaseUrl == other.providesBaseUrl &&
          handlesDeepLinks == other.handlesDeepLinks &&
          handlesBasicLogin == other.handlesBasicLogin &&
          handlesWebLogin == other.handlesWebLogin &&
          handlesMigration == other.handlesMigration;
}
