// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_resources_from_archive`, `extract_resources_with_content_from_bytes`, `extract_resources_with_content`, `find_chapter_name_from_toc`, `parse_epub_with_doc`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<EpubNovel> parseEpubFromPath({
  required String epubPath,
  required bool fullData,
}) => RustLib.instance.api.crateApiEpubParseEpubFromPath(
  epubPath: epubPath,
  fullData: fullData,
);

Future<EpubNovel> parseEpubFromBytes({
  required List<int> epubBytes,
  required bool fullData,
}) => RustLib.instance.api.crateApiEpubParseEpubFromBytes(
  epubBytes: epubBytes,
  fullData: fullData,
);

/// Get chapter content from EPUB by path
Future<String> getChapterContent({
  required String epubPath,
  required String chapterPath,
}) => RustLib.instance.api.crateApiEpubGetChapterContent(
  epubPath: epubPath,
  chapterPath: chapterPath,
);

class EpubChapter {
  final String name;
  final String content;
  final String path;

  const EpubChapter({
    required this.name,
    required this.content,
    required this.path,
  });

  @override
  int get hashCode => name.hashCode ^ content.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubChapter &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          content == other.content &&
          path == other.path;
}

class EpubNovel {
  final String name;
  final Uint8List? cover;
  final String? summary;
  final String? author;
  final String? artist;
  final List<EpubChapter> chapters;
  final List<EpubResource> images;
  final List<EpubResource> stylesheets;

  const EpubNovel({
    required this.name,
    this.cover,
    this.summary,
    this.author,
    this.artist,
    required this.chapters,
    required this.images,
    required this.stylesheets,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      cover.hashCode ^
      summary.hashCode ^
      author.hashCode ^
      artist.hashCode ^
      chapters.hashCode ^
      images.hashCode ^
      stylesheets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubNovel &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cover == other.cover &&
          summary == other.summary &&
          author == other.author &&
          artist == other.artist &&
          chapters == other.chapters &&
          images == other.images &&
          stylesheets == other.stylesheets;
}

class EpubResource {
  final String name;
  final Uint8List content;

  const EpubResource({required this.name, required this.content});

  @override
  int get hashCode => name.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubResource &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          content == other.content;
}
