// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The functions `crop_image` are not `pub`, thus are ignored.

Future<Uint8List> startCropping({required List<int> image}) =>
    RustLib.instance.api.crateApiImagecropStartCropping(image: image);
