// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_image_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SharedBufferWriter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `flush`, `fmt`, `fmt`, `fmt`, `write`

/// Extract metadata (including cover image) from a CBR/RAR file
Future<LocalRarMetadata> extractRarMetadata({required String archivePath}) =>
    RustLib.instance.api.crateApiRarExtractRarMetadata(
      archivePath: archivePath,
    );

/// Extract all images from a CBR/RAR archive
Future<LocalRarArchive> extractRarArchive({required String archivePath}) =>
    RustLib.instance.api.crateApiRarExtractRarArchive(archivePath: archivePath);

class LocalRarArchive {
  final String name;
  final Uint8List? coverImage;
  final List<LocalRarImage> images;
  final String path;

  const LocalRarArchive({
    required this.name,
    this.coverImage,
    required this.images,
    required this.path,
  });

  @override
  int get hashCode =>
      name.hashCode ^ coverImage.hashCode ^ images.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalRarArchive &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          coverImage == other.coverImage &&
          images == other.images &&
          path == other.path;
}

class LocalRarImage {
  final String name;
  final Uint8List image;

  const LocalRarImage({required this.name, required this.image});

  @override
  int get hashCode => name.hashCode ^ image.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalRarImage &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          image == other.image;
}

class LocalRarMetadata {
  final String name;
  final Uint8List coverImage;
  final String path;

  const LocalRarMetadata({
    required this.name,
    required this.coverImage,
    required this.path,
  });

  @override
  int get hashCode => name.hashCode ^ coverImage.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalRarMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          coverImage == other.coverImage &&
          path == other.path;
}
