import 'package:mangayomi/models/source_model.dart';

List<SourceModel> get mangathemesiaSourcesList => _mangathemesiaSourcesList;
List<SourceModel> _mangathemesiaSourcesList = [
  SourceModel(
      sourceName: "KomikLab",
      baseUrl: "https://komiklab.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: "AnimatedGlitchedScans",
      baseUrl: "https://anigliscans.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "ArenaScans",
  //     baseUrl: "https://arenascans.net",
  //     lang: "en",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl:
  //         'https://arenascans.net/wp-content/uploads/2023/02/arena-logo-1.png',
  //     isCloudflare: true),
  // SourceModel(
  //     sourceName: "AzureScans",
  //     baseUrl: "https://azuremanga.com",
  //     lang: "en",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: ''),

  SourceModel(
      sourceName: "Boosei",
      baseUrl: "https://boosei.net",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://cdn.boosei.com/wp-content/uploads/2021/11/Logo-Darkmode.png.webp',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "id"),
  SourceModel(
      sourceName: "Clayrer",
      baseUrl: "https://clayrer.net",
      lang: "es",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://clayrer.net/wp-content/uploads/2022/12/cropped-BackgroundEraser_20221205_145151639-1.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "es"),
  SourceModel(
      sourceName: "CosmicScans",
      baseUrl: "https://cosmicscans.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: "DiskusScan",
      baseUrl: "https://diskusscan.com",
      lang: "pt-br",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://diskusscan.com/wp-content/uploads/2022/12/imagem_2022-12-26_222007506.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "pt"),
  SourceModel(
      sourceName: "DuniaKomik",
      baseUrl: "https://duniakomik.id",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "id"),
  // SourceModel(
  //     sourceName: "FlameScans",
  //     baseUrl: "https://flamescans.fr",
  //     lang: "fr",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: ''),
  // SourceModel(
  //     sourceName: "GremoryMangas",
  //     baseUrl: "https://gremorymangas.com",
  //     lang: "es",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: 'https://gremorymangas.com/wp-content/uploads/2022/09/6941.png'),
  SourceModel(
      sourceName: "InfernalVoidScans",
      baseUrl: "https://void-scans.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      isCloudflare: true,
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),

  // SourceModel(
  //     sourceName: "Kiryuu",
  //     baseUrl: "https://kiryuu.id",
  //     lang: "id",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: '',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "id"),
  // SourceModel(
  //     sourceName: "KomikIndo",
  //     baseUrl: "https://komikindo.co",
  //     lang: "id",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: '',
  //     dateFormat: "MMM dd, yyyy",
  //     dateFormatLocale: "id"),
  SourceModel(
      sourceName: "KomikMama",
      baseUrl: "https://komikmama.co",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "id"),
  SourceModel(
      sourceName: "Komiku",
      baseUrl: "https://komiku.com",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl: 'https://komiku.com/wp-content/uploads/2022/03/logooo.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "id"),
  SourceModel(
      sourceName: "KumaScans (Kuma Translation)",
      baseUrl: "https://kumascans.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'http://kumascans.com/wp-content/uploads/2021/01/web-rawkuma-copy.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "MangaKita",
  //     baseUrl: "https://mangakita.net",
  //     lang: "id",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: '',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "MangaTale",
  //     baseUrl: "https://mangatale.co",
  //     lang: "id",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl:
  //         'http://mangatale.co/wp-content/uploads/2022/07/Group-of-23-Objects.png',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "en"),
  SourceModel(
      sourceName: "MangaYaro",
      baseUrl: "https://mangayaro.net",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://cache.mangayaro.net/wp-content/uploads/2021/07/20210723_193720.png.webp',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: "MangKomik",
      baseUrl: "https://mangkomik.net",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://cdn.mangkomik.net/wp-content/uploads/2023/02/image_2023-02-04_175453454-e1675527068905.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "id"),
  SourceModel(
      sourceName: "MangásChan",
      baseUrl: "https://mangaschan.com",
      lang: "pt-br",
      typeSource: TypeSource.mangathemesia,
      logoUrl: 'https://mangaschan.com/wp-content/uploads/Logo-web.webp',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "pt-br"),
  // SourceModel(
  //     sourceName: "ManhwaFreak",
  //     baseUrl: "https://manhwafreak.com",
  //     lang: "en",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl:
  //         'https://manhwafreak.com/wp-content/uploads/2022/09/New-Theme-Logo-2.png',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "en"),
  SourceModel(
      sourceName: "ManhwaList",
      baseUrl: "https://manhwalist.in",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "MasterKomik",
  //     baseUrl: "https://masterkomik.com",
  //     lang: "id",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: 'https://masterkomik.com/wp-content/uploads/2020/12/New-MK.png',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "id"),
  // SourceModel(
  //     sourceName: "Nekomik",
  //     baseUrl: "https://nekomik.com",
  //     lang: "id",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: '',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "PhantomScans",
  //     baseUrl: "https://phantomscans.com",
  //     lang: "en",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: '',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "PhoenixFansub",
  //     baseUrl: "https://phoenixfansub.com",
  //     lang: "es",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: '',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "es"),
  SourceModel(
      sourceName: "PiScans",
      baseUrl: "https://piscans.in",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://piscans.in/wp-content/uploads/2022/11/WM-Websitewq1.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "Rawkuma",
  //     baseUrl: "https://rawkuma.com/",
  //     lang: "ja",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: 'http://rawkuma.com/wp-content/uploads/2021/12/Rawkuma-Logo.png',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "en"),
  SourceModel(
      sourceName: "Readkomik",
      baseUrl: "https://readkomik.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://readkomik.com/wp-content/uploads/2021/01/PicsArt_01-23-03.51.01.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: "SuryaScans",
      baseUrl: "https://suryascans.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://suryascans.com/wp-content/uploads/2022/09/new-text-surya-logo1x.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  SourceModel(
      sourceName: "SushiScan",
      baseUrl: "https://sushiscan.net",
      lang: "fr",
      typeSource: TypeSource.mangathemesia,
      logoUrl: 'https://sushiscan.net/wp-content/uploads/SushiScanNewLogo.png',
      isCloudflare: true,
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "fr"),
  SourceModel(
      sourceName: "TsundokuTraduções",
      baseUrl: "https://tsundoku.com.br",
      lang: "pt-br",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://tsundoku.com.br/wp-content/uploads/2022/01/TsunBranca.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "pt-br"),
  SourceModel(
      sourceName: "TukangKomik",
      baseUrl: "https://tukangkomik.id",
      lang: "id",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://tukangkomik.id/wp-content/uploads/2022/03/tukangkomik-logo-1.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
  // SourceModel(
  //     sourceName: "WestManga",
  //     baseUrl: "https://westmanga.info",
  //     lang: "id",
  //     typeSource: TypeSource.mangathemesia,
  //     logoUrl: 'https://westmanga.info/wp-content/uploads/2021/01/LOGOxx-1.png',
  //     dateFormat: "MMMM dd, yyyy",
  //     dateFormatLocale: "en"),
  SourceModel(
      sourceName: "xCaliBRScans",
      baseUrl: "https://xcalibrscans.com",
      lang: "en",
      typeSource: TypeSource.mangathemesia,
      logoUrl:
          'https://xcalibrscans.com/wp-content/uploads/2021/06/xcalibr-dark-v3.png',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "en"),
];
