app_id: 6CB26FFA-E72B-42C3-91E8-594940031CA2
publisher: kodjodevf
publisher_url: https://github.com/kodjodevf/mangayomi/
display_name: Mangayomi
create_desktop_icon: true
locales:
  - en
script_template: inno_setup.iss