name: Build & Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build-and-release-windows-exe:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install the CLI tool
        run: cargo install 'flutter_rust_bridge_codegen'

      - name: flutter pub get
        run: flutter pub get

      - name: Enable dart_distributor
        run: dart pub global activate flutter_distributor

      - name: Update PATH
        run: echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> ~/.bashrc

      - name: build windows
        run: |
          flutter_distributor package --platform windows --targets exe --artifact-name 'Mangayomi-${{ github.ref_name }}-windows.exe'

      - name: upload artifact windows exe
        uses: actions/upload-artifact@v3
        with:
          path: ./**/Mangayomi-*.exe

      - name: release package windows exe
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./**/Mangayomi-*.exe
          allowUpdates: true
